CREATE TYPE "card_rarity" AS ENUM (
  'common',
  'rare',
  'epic',
  'mythic'
);

CREATE TYPE "payment_method" AS ENUM (
  'usd',
  'bitcoin',
  'etherium'
);

CREATE TYPE "payment_status" AS ENUM (
  'pending',
  'processing',
  'refunded',
  'success',
  'failure',
  'canceled'
);

CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar(255) NOT NULL,
  "password" varchar(255) NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "cards" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "rarity" card_rarity NOT NULL,
  "power" integer NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "pack" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) NOT NULL,
  "price" numeric(10,2) NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "purchased_packs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "pack_id" integer NOT NULL,
  "is_opened" bool NOT NULL DEFAULT false,
  "transaction_id" integer NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "opened_at" timestamp
);

CREATE TABLE "opened_pack_cards" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "purchased_pack_id" integer NOT NULL,
  "card_id" integer NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "ticket" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) NOT NULL,
  "price" numeric(10,2) NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "purchased_tickets" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "ticket_id" integer NOT NULL,
  "transaction_id" integer NOT NULL,
  "is_used" bool NOT NULL DEFAULT false,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "used_at" timestamp
);

CREATE TABLE "transactions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "payment_method" payment_method NOT NULL,
  "amount" numeric(10,2) NOT NULL,
  "user_id" integer NOT NULL,
  "pack_id" integer NOT NULL,
  "ticket_id" integer NOT NULL,
  "payment_id" VARCHAR(255),
  "status" payment_status NOT NULL DEFAULT 'pending',
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE "purchased_packs" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "purchased_packs" ADD FOREIGN KEY ("pack_id") REFERENCES "pack" ("id");

ALTER TABLE "purchased_packs" ADD FOREIGN KEY ("transaction_id") REFERENCES "transactions" ("id");

ALTER TABLE "opened_pack_cards" ADD FOREIGN KEY ("purchased_pack_id") REFERENCES "purchased_packs" ("id");

ALTER TABLE "opened_pack_cards" ADD FOREIGN KEY ("card_id") REFERENCES "cards" ("id");

ALTER TABLE "purchased_tickets" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "purchased_tickets" ADD FOREIGN KEY ("ticket_id") REFERENCES "ticket" ("id");

ALTER TABLE "purchased_tickets" ADD FOREIGN KEY ("transaction_id") REFERENCES "transactions" ("id");

ALTER TABLE "transactions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "transactions" ADD FOREIGN KEY ("ticket_id") REFERENCES "ticket" ("id");

ALTER TABLE "transactions" ADD FOREIGN KEY ("pack_id") REFERENCES "pack" ("id");
